apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-go
  labels:
    app: example-go
  namespace: subscriptions
spec:
  selector:
    matchLabels:
      app: example-go
  template:
    metadata:
      labels:
        app: example-go
    spec:
      containers:
        - name: example-go
          image: example-go-image
          ports:
            - containerPort: 8080
        - env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: t35tP455w0rd
            - name: POSTGRES_DB
              value: subscriptions
            - name: POSTGRES_HOST
              value: postgres1
          image: example-go
          name: example-go
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: example-go-test
  name: example-go-test
  namespace: subscriptions
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: example-go
status:
  loadBalancer: {}

