apiVersion: batch/v1
kind: CronJob
metadata:
  name: subscription-evaluation-cron
spec:
  schedule: "* 9-17 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: subscription-evaluation-cron
              image: alpine:3.12
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - apk add --update curl && curl -v -X POST http://go-service:8080/evaluate-subscriptions
          restartPolicy: OnFailure
