apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: local-go-image
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: go-service
  name: go-service
  namespace: subscriptions
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: go-app
status:
  loadBalancer: {}

