apiVersion: v1
kind: Service
metadata:
  name: kafka-kafdrop-service
  labels:
    app: kafka-kafdrop
spec:
  ports:
    - protocol: "TCP"
      port: 9000
      name: server
  selector:
    app: kafka-kafdrop
  type: LoadBalancer