version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - subscription-newtork
    env_file:
      - .env
    restart: on-failure
    volumes:
      - .:/app

  postgres:
    image: postgres:14.1-alpine
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 20
    ports:
      - '1234:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    env_file:
      - .env
    networks:
      - subscription-newtork
volumes:
  postgres-data:

networks:
  subscription-newtork:
    driver: bridge