---
apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-cm
  labels:
    name: krakend-cm
data:
  krakend.json: |
    {
      "version": 2,
      "extra_config": {},
      "timeout": "3000ms",
      "cache_ttl": "300s",
      "host": [
        "http://example-go-test:8080"
      ],
      "output_encoding": "json",
      "name": "MyTest",
      "endpoints": [
        {
          "endpoint": "/log",
          "method": "POST",
          "output_encoding": "json",
          "extra_config": {},
          "backend": [
            {
              "url_pattern": "/log-action",
              "method": "POST",
              "whitelist": [
              ],
              "extra_config": {}
            }
          ],
          "querystring_params": [
            
          ]
        }
      ]
    }
